#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

 cookbook 'ark'
 cookbook 'zsh'
 cookbook 'apt'
 cookbook 'java'
 cookbook 'subversion'
 cookbook 'maven'
 cookbook 'tomcat'
 cookbook 'database'
# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
