#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

 cookbook 'ark'
 cookbook 'zsh'
 cookbook 'apt'
 cookbook 'java'
 cookbook 'subversion'
 cookbook 'maven'
 cookbook 'tomcat'
 cookbook 'database'

 cookbook 'mysql',
   :git => 'https://github.com/mztaylor/mysql'
